name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    name: Print username
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.username }}
