name: Check Commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-signed-off-by:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env
        run: |
          echo "GITHUB_CONTEXT: ${GITHUB_CONTEXT}"
          echo "message: ${message}"
          echo "message2: ${message2}"
          echo "body_message: ${body_message}"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          message: ${{ github.event.head_commit.message }}
          message2: ${{ github.event.commits[0].message }}
          body_message: ${{ github.event.pull_request.body }}
      - run: |
          ROLL_BACK_COUNT=$(( ${{ github.event.pull_request.commits }} - 1 ))
          git log --format=%B -n 1 ${{ github.event.after }}~${ROLL_BACK_COUNT} > main_commit_msg
          cat main_commit_msg
      - run: |
          git log --format=%B -n 1 ${{ github.event.after }} > main_commit_msg
          cat main_commit_msg

