name: Check PR Commit

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get commit body
        run: |
          git log origin/${{ github.base_ref }}..HEAD --format=%b > commit_msg.txt
          tail -n +2 commit_msg.txt > commit_body.txt
      - name: Check signed-off
        run: |
          count=$(cat commit_body.txt | grep 'Signed-off-by:' | wc -l)
          if [[ ! "$count" -ge "1" ]]; then
            exit 1
          fi

          echo "Signed-off-by is OK"
      - name: Check body words
        if: always()
        run: |
          count=$(cat commit_body.txt | sed '/Signed-off-by:/d' | wc -w)
          echo "Commit body word check: $count words"
          if [[ "$count" -lt "5" ]]; then
            exit 1
          fi

          echo "Body words count is OK"
