name: pull request target test

on:
  pull_request_target

jobs:
  test:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: First step
        run: echo "pull request target test"

      - uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: |
                '[CI] Finished all test (debian bionic)'
                'abcd'
                'efgh'
            })
