name: pull request target test

on:
  pull_request_target

jobs:
  test:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: First step
        run: |
          mkdir -p /tmp/OUTBOUND
          echo "pull request target test" > /tmp/OUTBOUND/test_result.txt

      - uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v3
        env:
          SHA: ${{ github.sha }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fileContent = ""

            const reader = new FileReader()
            reader.onload = functon() {
              fileContent = reader.result
              console.log('Content', fileContent)
            }
            reader.onerror = function() {
              console.log(reader.error)
            }

            reader.readAsText('/tmp/OUTBOUND/test_result.txt')
            const beginComment = '[CI] Finished all test (debian bionic)'
            beginComment.concat(process.env.SHA)

            const body = `${beginComment}\n\n${fileContent}`

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
