name: Create release

on:
  workflow_dispatch:    # Allow manual triggers
    inputs:
      tags:
        description: 'Release tag'
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Release tag version`,
              body: `Let's release tag version`
            }).then(response => {
              console.log(response.data);
            })