name: workflow run test

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: First step
        run: echo "pull request target test"

      - uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '[CI] Finished all test (debian bionic)'
            })
